import Image from "next/image";
import { ArrowRight } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { createSupabaseClient } from "@/lib/supabase/client";
import type { AppLocale } from "@/i18n/routing";

type PromotionPlacement = "top" | "video" | "bottom";
type Slot = "top_banner" | "bottom_banner" | "video";
type Row = { id: string; slot: Slot; media_type: "image" | "video"; storage_path: string; title_zh: string|null; title_en: string|null; description_zh: string|null; description_en: string|null; cta_zh: string|null; cta_en: string|null; href: string|null; media_alt_zh: string|null; media_alt_en: string|null };
const slots: Record<PromotionPlacement, Slot[]> = { top: ["top_banner"], video: ["video"], bottom: ["bottom_banner"] };
async function loadPublished(wanted: Slot[]) { try { const db=createSupabaseClient(); const {data,error}=await db.from("homepage_promotions").select("*").eq("published",true).in("slot",wanted); return error ? [] : (data as Row[] ?? []); } catch { return []; } }
function url(path: string) { const base=process.env.NEXT_PUBLIC_SUPABASE_URL; return base&&path ? `${base.replace(/\/$/,"")}/storage/v1/object/public/heritage-media/${path}` : ""; }
function text(row: Row, locale: AppLocale) { return { title: locale === "zh" ? row.title_zh : row.title_en, description: locale === "zh" ? row.description_zh : row.description_en, cta: locale === "zh" ? row.cta_zh : row.cta_en, alt: locale === "zh" ? row.media_alt_zh : row.media_alt_en }; }
function CTA({row,locale}:{row:Row;locale:AppLocale}) { const c=text(row,locale); return row.href&&c.cta ? <Link href={row.href} className="group inline-flex items-center gap-2 text-sm font-medium text-[#24483c] transition-colors hover:text-[#9d4b40]">{c.cta}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link> : null; }
function Media({row,locale,className,sizes}:{row:Row;locale:AppLocale;className:string;sizes:string}) { const src=url(row.storage_path); if(!src)return null; return row.media_type === "video" ? <video className={className} src={src} controls playsInline preload="metadata"/> : <Image src={src} alt={text(row,locale).alt||text(row,locale).title||""} fill sizes={sizes} className={className}/>; }
function Banner({row,locale,label}:{row:Row;locale:AppLocale;label:string}) { const c=text(row,locale); return <section aria-label={label} className="bg-[#f7f5f0] px-5 py-10 text-[#191f1c] lg:px-12 lg:py-14"><div className="mx-auto grid max-w-[1344px] overflow-hidden rounded-[8px] border border-[#24483c]/10 bg-[#f1efe9] shadow-[0_12px_32px_rgba(31,47,40,0.08)] md:aspect-[16/5] md:grid-cols-[58%_42%]"><div className="relative aspect-[16/5] min-h-[180px] bg-[#e8ebe5] md:aspect-auto md:min-h-0"><Media row={row} locale={locale} sizes="(min-width: 768px) 58vw, calc(100vw - 40px)" className="h-full w-full object-contain"/></div><div className="flex min-h-[220px] flex-col justify-center px-6 py-8 sm:px-9 md:min-h-0 md:px-10 md:py-6 lg:px-14">{c.title&&<h2 className="serif-title text-2xl font-normal leading-tight sm:text-3xl lg:text-4xl">{c.title}</h2>}{c.description&&<p className="mt-4 max-w-md text-sm leading-7 text-[#65716b]">{c.description}</p>}<div className="mt-6"><CTA row={row} locale={locale}/></div></div></div></section>; }
function VideoFeature({row,locale,label}:{row:Row;locale:AppLocale;label:string}) { const c=text(row,locale); return <section aria-label={label} className="bg-[#f7f5f0] px-5 py-12 text-[#191f1c] lg:px-12 lg:py-16"><div className="mx-auto max-w-[1344px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div>{c.title&&<h2 className="serif-title text-2xl font-normal leading-tight sm:text-3xl">{c.title}</h2>}{c.description&&<p className="mt-3 max-w-2xl text-sm leading-7 text-[#65716b]">{c.description}</p>}</div><CTA row={row} locale={locale}/></div><div className="group relative aspect-video overflow-hidden rounded-[8px] border border-[#24483c]/10 bg-[#171512] shadow-[0_12px_32px_rgba(31,47,40,0.08)] transition-transform duration-300 hover:-translate-y-1"><Media row={row} locale={locale} sizes="(min-width: 768px) 90vw, calc(100vw - 40px)" className="h-full w-full object-contain"/></div></div></section>; }
export async function HomePromotions({placement,locale}:{placement:PromotionPlacement;locale:AppLocale}) { const loaded=await loadPublished(slots[placement]); const rows=loaded.filter((row)=>row.media_type === "image" || row.media_type === "video"); if(!rows.length)return null; const label=placement === "top" ? (locale === "en" ? "Featured heritage promotion" : "非遗专题宣传") : placement === "video" ? (locale === "en" ? "Heritage video promotion" : "非遗视频宣传") : (locale === "en" ? "Cultural partnership promotion" : "文化合作宣传"); return placement === "video" ? <VideoFeature row={rows[0]} locale={locale} label={label}/> : <Banner row={rows[0]} locale={locale} label={label}/>; }
